replicaCount: 1

fullnameOverride: "keycloak"

auth:
  adminUser: "admin"
  adminPassword: "changeme"

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1"

persistence:
  enabled: true
  size: 10Gi

ingress:
  enabled: true
  hostname: iam.karned.bzh
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls: true