apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.applicationName }}-config
  labels:
    app: {{ .Values.global.applicationName }}
data:
  KC_DB: {{ .Values.keycloak.database.type }}
  KC_DB_HOST: {{ .Values.keycloak.database.host }}
  KC_DB_PORT: {{ .Values.keycloak.database.port | quote }}
  KC_DB_DATABASE: {{ .Values.keycloak.database.name }}