{{- if .Values.keycloak.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.applicationName }}-data
  labels:
    app: {{ .Values.global.applicationName }}
spec:
  accessModes:
    - {{ .Values.keycloak.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.keycloak.persistence.size }}
  storageClassName: {{ .Values.keycloak.persistence.storageClass }}
{{- end }}