apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.applicationName }}
  labels:
    app: {{ .Values.global.applicationName }}
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
  - port: {{ .Values.keycloak.service.port }}
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ .Values.global.applicationName }}